### ISSUE TITLE
Reference to your project

### ISSUE THREAD

**Issue by jonathf** [obersteiner/sparseSpACE#1]
Hey!

I am the maintainer for Chaospy which you are using as a dependency.
I keep a list of related projects on the Github frontpage:
https://github.com/jonathf/chaospy#related-projects
Do you guys mind if I add sparseSpACE to that list?

**Comment by jonathf** [comment]
Also, hi @flo2k.

**Comment by flo2k** [comment]
@jonathf  hi. I think this is a good idea.

**Comment by obersteiner** [comment]
Hi,

of course you can add the project to the list.

**Comment by jonathf** [comment]
Great. Done.
